server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/leave_scheduler?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Jagadeesh@09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=leaveSchedulerSecretKey2024VeryLongAndSecureSecretKeyForJWT
app.jwt.expiration=86400000
app.bootstrap.admin-key=SubbuAdminSetup2026

# Mail
app.mail.enabled=false
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=subashbr895@gmail.com
# spring.mail.password=xdouqbpqrbptnnsl
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# CORS
app.cors.allowed-origins=http://localhost:3000

# Leave Policy
app.leave.annual-days=21
app.leave.sick-days=10
app.leave.casual-days=7
